services:
  app:
    build:
      context: .
      args:
        - DEV=True
    ports:
      - "8000:8000"
    volumes:
      - './:/app'
    command: >
      sh -c '
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000'
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DEBUG=1
    depends_on:
        - db

  db:
    image: postgres:15-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '5432:5432'

volumes:
  dev-db-data:
